{% set name = "sspilib" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sspilib-{{ version }}.tar.gz
  sha256: 4d6cd4290ca82f40705efeb5e9107f7abcd5e647cb201a3d04371305938615b8

build:
  skip: true  # [not win or py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=3.0.0,<4.0.0
    - setuptools >=61.0.0
    - pip
  run:
    - python

test:
  imports:
    - sspilib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/sspilib
  summary: SSPI API bindings for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
