{% set name = "sspilib" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sspilib-{{ version }}.tar.gz
  sha256: b482b3be8dc30e086f89e13831139129c022f90f6e7c0603b3c60209d9a4561d

build:
  skip: true  # [not win or py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=3.0.0,<4.0.0
    - setuptools >=77.0.0
    - pip
  run:
    - python

test:
  imports:
    - sspilib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/sspilib
  summary: SSPI API bindings for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
